server:
  port: 2204

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=agency
    username: postgres
    password: 2203
  jpa:
    show-sql: true
    generate-ddl: true

#kafka
kafka:
  topic: MoveUsers
  group-id: Logger
  port:
    kafka: localhost:9092
    zookeeper: localhost:2181

